import type { DoorKariItem } from "@/data/door_kari_item";
import type { HozuriItem } from "@/data/hozuri_item";
import type { LeaveRequest } from "@/data/leave_request";
import { MOCK_HOZURI_DATA } from "./mock_hozuri_data";
import type { AttendenceStatusDto } from "@/data/attendence_status_dto";

let searchParams = new URLSearchParams(window.location.search);
export let TOKEN = searchParams.get('token')?.toString() || '';
export let COOKIE = searchParams.get('cookie')?.toString() || '';
const IS_DEV = (import.meta.env.DEV);
const HOZURI_LOCAL_STORAGE = 'hozuri-local-storage';
const delay = (ms: number): Promise<void> => {
    return new Promise((resolve, _) => {
        setTimeout(() => {
            resolve();
        }, ms);
    });
};
export const ATTENDENCE_API = {
    async getHozuriList(): Promise<HozuriItem[]> {
        let str = window.localStorage.getItem(HOZURI_LOCAL_STORAGE);
        if (str == undefined)
            str = '[]';
        return JSON.parse(str) as HozuriItem[];
    },
    async setHozuriList(list: HozuriItem[]) {
        window.localStorage.setItem(HOZURI_LOCAL_STORAGE, JSON.stringify(list));
    },
    async getDoorKariList(): Promise<DoorKariItem[]> {
        if (IS_DEV) {
            await delay(1_000);
            return [
                {
                    "number": "1563373",
                    "issueDate": 1763337600000,
                    "issueDate_Display": "‎1404/08/26‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1763283600000,
                    "fromDateTime_Display": "‎1404/08/25‏",
                    "fromTime": "09:00",
                    "toDateTime": 1763319600000,
                    "toDateTime_Display": "‎1404/08/25‏",
                    "toTime": "19:00",
                    "durationMinutes": "10:00",
                    "extensionDateTime": 1763319600000,
                    "extensionDateTime_Display": "‎1404/08/25‏",
                    "status": 1,
                    "status_Display": "Registered",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "doorkari",
                    "id": 1686323
                },
                {
                    "number": "1558367",
                    "issueDate": 1762905600000,
                    "issueDate_Display": "‎1404/08/21‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1762077600000,
                    "fromDateTime_Display": "‎1404/08/11‏",
                    "fromTime": "10:00",
                    "toDateTime": 1762110000000,
                    "toDateTime_Display": "‎1404/08/11‏",
                    "toTime": "19:00",
                    "durationMinutes": "09:00",
                    "extensionDateTime": 1762110000000,
                    "extensionDateTime_Display": "‎1404/08/11‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "فرینا خلیقی زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1680754
                },
                {
                    "number": "1558366",
                    "issueDate": 1762905600000,
                    "issueDate_Display": "‎1404/08/21‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1761991200000,
                    "fromDateTime_Display": "‎1404/08/10‏",
                    "fromTime": "10:00",
                    "toDateTime": 1762023600000,
                    "toDateTime_Display": "‎1404/08/10‏",
                    "toTime": "19:00",
                    "durationMinutes": "09:00",
                    "extensionDateTime": 1762023600000,
                    "extensionDateTime_Display": "‎1404/08/10‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "فرینا خلیقی زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1680753
                },
                {
                    "number": "1556971",
                    "issueDate": 1762819200000,
                    "issueDate_Display": "‎1404/08/20‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1762765200000,
                    "fromDateTime_Display": "‎1404/08/19‏",
                    "fromTime": "09:00",
                    "toDateTime": 1762801200000,
                    "toDateTime_Display": "‎1404/08/19‏",
                    "toTime": "19:00",
                    "durationMinutes": "10:00",
                    "extensionDateTime": 1762801200000,
                    "extensionDateTime_Display": "‎1404/08/19‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1678212
                },
                {
                    "number": "1555269",
                    "issueDate": 1762646400000,
                    "issueDate_Display": "‎1404/08/18‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1762592400000,
                    "fromDateTime_Display": "‎1404/08/17‏",
                    "fromTime": "09:00",
                    "toDateTime": 1762628400000,
                    "toDateTime_Display": "‎1404/08/17‏",
                    "toTime": "19:00",
                    "durationMinutes": "10:00",
                    "extensionDateTime": 1762628400000,
                    "extensionDateTime_Display": "‎1404/08/17‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1676180
                },
                {
                    "number": "1555268",
                    "issueDate": 1762646400000,
                    "issueDate_Display": "‎1404/08/18‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1762678800000,
                    "fromDateTime_Display": "‎1404/08/18‏",
                    "fromTime": "09:00",
                    "toDateTime": 1762714800000,
                    "toDateTime_Display": "‎1404/08/18‏",
                    "toTime": "19:00",
                    "durationMinutes": "10:00",
                    "extensionDateTime": 1762714800000,
                    "extensionDateTime_Display": "‎1404/08/18‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1676179
                },
                {
                    "number": "1549824",
                    "issueDate": 1762214400000,
                    "issueDate_Display": "‎1404/08/13‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1762160400000,
                    "fromDateTime_Display": "‎1404/08/12‏",
                    "fromTime": "09:00",
                    "toDateTime": 1762196400000,
                    "toDateTime_Display": "‎1404/08/12‏",
                    "toTime": "19:00",
                    "durationMinutes": "10:00",
                    "extensionDateTime": 1762196400000,
                    "extensionDateTime_Display": "‎1404/08/12‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1669286
                },
                {
                    "number": "1540892",
                    "issueDate": 1761609600000,
                    "issueDate_Display": "‎1404/08/06‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1761555600000,
                    "fromDateTime_Display": "‎1404/08/05‏",
                    "fromTime": "09:00",
                    "toDateTime": 1761591600000,
                    "toDateTime_Display": "‎1404/08/05‏",
                    "toTime": "19:00",
                    "durationMinutes": "10:00",
                    "extensionDateTime": 1761591600000,
                    "extensionDateTime_Display": "‎1404/08/05‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1658994
                },
                {
                    "number": "1540884",
                    "issueDate": 1761609600000,
                    "issueDate_Display": "‎1404/08/06‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1761469200000,
                    "fromDateTime_Display": "‎1404/08/04‏",
                    "fromTime": "09:00",
                    "toDateTime": 1761505200000,
                    "toDateTime_Display": "‎1404/08/04‏",
                    "toTime": "19:00",
                    "durationMinutes": "10:00",
                    "extensionDateTime": 1761505200000,
                    "extensionDateTime_Display": "‎1404/08/04‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1658985
                },
                {
                    "number": "1540882",
                    "issueDate": 1761609600000,
                    "issueDate_Display": "‎1404/08/06‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1761382800000,
                    "fromDateTime_Display": "‎1404/08/03‏",
                    "fromTime": "09:00",
                    "toDateTime": 1761418800000,
                    "toDateTime_Display": "‎1404/08/03‏",
                    "toTime": "19:00",
                    "durationMinutes": "10:00",
                    "extensionDateTime": 1761418800000,
                    "extensionDateTime_Display": "‎1404/08/03‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1658983
                },
                {
                    "number": "1540876",
                    "issueDate": 1761609600000,
                    "issueDate_Display": "‎1404/08/06‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1760950800000,
                    "fromDateTime_Display": "‎1404/07/28‏",
                    "fromTime": "09:00",
                    "toDateTime": 1760986800000,
                    "toDateTime_Display": "‎1404/07/28‏",
                    "toTime": "19:00",
                    "durationMinutes": "10:00",
                    "extensionDateTime": 1760986800000,
                    "extensionDateTime_Display": "‎1404/07/28‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1658977
                },
                {
                    "number": "1540870",
                    "issueDate": 1761609600000,
                    "issueDate_Display": "‎1404/08/06‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1760864400000,
                    "fromDateTime_Display": "‎1404/07/27‏",
                    "fromTime": "09:00",
                    "toDateTime": 1760896800000,
                    "toDateTime_Display": "‎1404/07/27‏",
                    "toTime": "18:00",
                    "durationMinutes": "09:00",
                    "extensionDateTime": 1760896800000,
                    "extensionDateTime_Display": "‎1404/07/27‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1658971
                },
                {
                    "number": "1525618",
                    "issueDate": 1757376000000,
                    "issueDate_Display": "‎1404/06/18‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1760347800000,
                    "fromDateTime_Display": "‎1404/07/21‏",
                    "fromTime": "09:30",
                    "toDateTime": 1760382000000,
                    "toDateTime_Display": "‎1404/07/21‏",
                    "toTime": "19:00",
                    "durationMinutes": "09:30",
                    "extensionDateTime": 1760382000000,
                    "extensionDateTime_Display": "‎1404/07/21‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1642609
                },
                {
                    "number": "1525617",
                    "issueDate": 1757376000000,
                    "issueDate_Display": "‎1404/06/18‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1760261400000,
                    "fromDateTime_Display": "‎1404/07/20‏",
                    "fromTime": "09:30",
                    "toDateTime": 1760295600000,
                    "toDateTime_Display": "‎1404/07/20‏",
                    "toTime": "19:00",
                    "durationMinutes": "09:30",
                    "extensionDateTime": 1760295600000,
                    "extensionDateTime_Display": "‎1404/07/20‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1642608
                },
                {
                    "number": "1525616",
                    "issueDate": 1757376000000,
                    "issueDate_Display": "‎1404/06/18‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1760175000000,
                    "fromDateTime_Display": "‎1404/07/19‏",
                    "fromTime": "09:30",
                    "toDateTime": 1760209200000,
                    "toDateTime_Display": "‎1404/07/19‏",
                    "toTime": "19:00",
                    "durationMinutes": "09:30",
                    "extensionDateTime": 1760209200000,
                    "extensionDateTime_Display": "‎1404/07/19‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1642607
                },
                {
                    "number": "1525613",
                    "issueDate": 1757376000000,
                    "issueDate_Display": "‎1404/06/18‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1759915800000,
                    "fromDateTime_Display": "‎1404/07/16‏",
                    "fromTime": "09:30",
                    "toDateTime": 1759950000000,
                    "toDateTime_Display": "‎1404/07/16‏",
                    "toTime": "19:00",
                    "durationMinutes": "09:30",
                    "extensionDateTime": 1759950000000,
                    "extensionDateTime_Display": "‎1404/07/16‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1642604
                },
                {
                    "number": "1525612",
                    "issueDate": 1757376000000,
                    "issueDate_Display": "‎1404/06/18‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1759829400000,
                    "fromDateTime_Display": "‎1404/07/15‏",
                    "fromTime": "09:30",
                    "toDateTime": 1759863600000,
                    "toDateTime_Display": "‎1404/07/15‏",
                    "toTime": "19:00",
                    "durationMinutes": "09:30",
                    "extensionDateTime": 1759863600000,
                    "extensionDateTime_Display": "‎1404/07/15‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1642603
                },
                {
                    "number": "1525611",
                    "issueDate": 1757376000000,
                    "issueDate_Display": "‎1404/06/18‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1759743000000,
                    "fromDateTime_Display": "‎1404/07/14‏",
                    "fromTime": "09:30",
                    "toDateTime": 1759777200000,
                    "toDateTime_Display": "‎1404/07/14‏",
                    "toTime": "19:00",
                    "durationMinutes": "09:30",
                    "extensionDateTime": 1759777200000,
                    "extensionDateTime_Display": "‎1404/07/14‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1642602
                },
                {
                    "number": "1525610",
                    "issueDate": 1757376000000,
                    "issueDate_Display": "‎1404/06/18‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1759656600000,
                    "fromDateTime_Display": "‎1404/07/13‏",
                    "fromTime": "09:30",
                    "toDateTime": 1759690800000,
                    "toDateTime_Display": "‎1404/07/13‏",
                    "toTime": "19:00",
                    "durationMinutes": "09:30",
                    "extensionDateTime": 1759690800000,
                    "extensionDateTime_Display": "‎1404/07/13‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1642601
                },
                {
                    "number": "1525609",
                    "issueDate": 1757376000000,
                    "issueDate_Display": "‎1404/06/18‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1759570200000,
                    "fromDateTime_Display": "‎1404/07/12‏",
                    "fromTime": "09:30",
                    "toDateTime": 1759604400000,
                    "toDateTime_Display": "‎1404/07/12‏",
                    "toTime": "19:00",
                    "durationMinutes": "09:30",
                    "extensionDateTime": 1759604400000,
                    "extensionDateTime_Display": "‎1404/07/12‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1642600
                },
                {
                    "number": "1525606",
                    "issueDate": 1757376000000,
                    "issueDate_Display": "‎1404/06/18‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1759311000000,
                    "fromDateTime_Display": "‎1404/07/09‏",
                    "fromTime": "09:30",
                    "toDateTime": 1759345200000,
                    "toDateTime_Display": "‎1404/07/09‏",
                    "toTime": "19:00",
                    "durationMinutes": "09:30",
                    "extensionDateTime": 1759345200000,
                    "extensionDateTime_Display": "‎1404/07/09‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1642597
                },
                {
                    "number": "1525605",
                    "issueDate": 1757376000000,
                    "issueDate_Display": "‎1404/06/18‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1759224600000,
                    "fromDateTime_Display": "‎1404/07/08‏",
                    "fromTime": "09:30",
                    "toDateTime": 1759258800000,
                    "toDateTime_Display": "‎1404/07/08‏",
                    "toTime": "19:00",
                    "durationMinutes": "09:30",
                    "extensionDateTime": 1759258800000,
                    "extensionDateTime_Display": "‎1404/07/08‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1642596
                },
                {
                    "number": "1525604",
                    "issueDate": 1757376000000,
                    "issueDate_Display": "‎1404/06/18‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1759138200000,
                    "fromDateTime_Display": "‎1404/07/07‏",
                    "fromTime": "09:30",
                    "toDateTime": 1759172400000,
                    "toDateTime_Display": "‎1404/07/07‏",
                    "toTime": "19:00",
                    "durationMinutes": "09:30",
                    "extensionDateTime": 1759172400000,
                    "extensionDateTime_Display": "‎1404/07/07‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1642595
                },
                {
                    "number": "1525603",
                    "issueDate": 1757376000000,
                    "issueDate_Display": "‎1404/06/18‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1759051800000,
                    "fromDateTime_Display": "‎1404/07/06‏",
                    "fromTime": "09:30",
                    "toDateTime": 1759086000000,
                    "toDateTime_Display": "‎1404/07/06‏",
                    "toTime": "19:00",
                    "durationMinutes": "09:30",
                    "extensionDateTime": 1759086000000,
                    "extensionDateTime_Display": "‎1404/07/06‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1642594
                },
                {
                    "number": "1525602",
                    "issueDate": 1757376000000,
                    "issueDate_Display": "‎1404/06/18‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1758965400000,
                    "fromDateTime_Display": "‎1404/07/05‏",
                    "fromTime": "09:30",
                    "toDateTime": 1758999600000,
                    "toDateTime_Display": "‎1404/07/05‏",
                    "toTime": "19:00",
                    "durationMinutes": "09:30",
                    "extensionDateTime": 1758999600000,
                    "extensionDateTime_Display": "‎1404/07/05‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1642593
                },
                {
                    "number": "1525599",
                    "issueDate": 1757376000000,
                    "issueDate_Display": "‎1404/06/18‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1758706200000,
                    "fromDateTime_Display": "‎1404/07/02‏",
                    "fromTime": "09:30",
                    "toDateTime": 1758740400000,
                    "toDateTime_Display": "‎1404/07/02‏",
                    "toTime": "19:00",
                    "durationMinutes": "09:30",
                    "extensionDateTime": 1758740400000,
                    "extensionDateTime_Display": "‎1404/07/02‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1642590
                },
                {
                    "number": "1525598",
                    "issueDate": 1757376000000,
                    "issueDate_Display": "‎1404/06/18‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1758619800000,
                    "fromDateTime_Display": "‎1404/07/01‏",
                    "fromTime": "09:30",
                    "toDateTime": 1758654000000,
                    "toDateTime_Display": "‎1404/07/01‏",
                    "toTime": "19:00",
                    "durationMinutes": "09:30",
                    "extensionDateTime": 1758654000000,
                    "extensionDateTime_Display": "‎1404/07/01‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1642589
                },
                {
                    "number": "1525597",
                    "issueDate": 1757376000000,
                    "issueDate_Display": "‎1404/06/18‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1758533400000,
                    "fromDateTime_Display": "‎1404/06/31‏",
                    "fromTime": "09:30",
                    "toDateTime": 1758567600000,
                    "toDateTime_Display": "‎1404/06/31‏",
                    "toTime": "19:00",
                    "durationMinutes": "09:30",
                    "extensionDateTime": 1758567600000,
                    "extensionDateTime_Display": "‎1404/06/31‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1642588
                },
                {
                    "number": "1525596",
                    "issueDate": 1757376000000,
                    "issueDate_Display": "‎1404/06/18‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1758447000000,
                    "fromDateTime_Display": "‎1404/06/30‏",
                    "fromTime": "09:30",
                    "toDateTime": 1758481200000,
                    "toDateTime_Display": "‎1404/06/30‏",
                    "toTime": "19:00",
                    "durationMinutes": "09:30",
                    "extensionDateTime": 1758481200000,
                    "extensionDateTime_Display": "‎1404/06/30‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1642587
                },
                {
                    "number": "1525595",
                    "issueDate": 1757376000000,
                    "issueDate_Display": "‎1404/06/18‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1758360600000,
                    "fromDateTime_Display": "‎1404/06/29‏",
                    "fromTime": "09:30",
                    "toDateTime": 1758394800000,
                    "toDateTime_Display": "‎1404/06/29‏",
                    "toTime": "19:00",
                    "durationMinutes": "09:30",
                    "extensionDateTime": 1758394800000,
                    "extensionDateTime_Display": "‎1404/06/29‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1642586
                },
                {
                    "number": "1525592",
                    "issueDate": 1757376000000,
                    "issueDate_Display": "‎1404/06/18‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1758101400000,
                    "fromDateTime_Display": "‎1404/06/26‏",
                    "fromTime": "09:30",
                    "toDateTime": 1758135600000,
                    "toDateTime_Display": "‎1404/06/26‏",
                    "toTime": "19:00",
                    "durationMinutes": "09:30",
                    "extensionDateTime": 1758135600000,
                    "extensionDateTime_Display": "‎1404/06/26‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1642583
                },
                {
                    "number": "1525578",
                    "issueDate": 1760227200000,
                    "issueDate_Display": "‎1404/07/20‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1757755800000,
                    "fromDateTime_Display": "‎1404/06/22‏",
                    "fromTime": "09:30",
                    "toDateTime": 1757790000000,
                    "toDateTime_Display": "‎1404/06/22‏",
                    "toTime": "19:00",
                    "durationMinutes": "09:30",
                    "extensionDateTime": 1757790000000,
                    "extensionDateTime_Display": "‎1404/06/22‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1642567
                },
                {
                    "number": "1489719",
                    "issueDate": 1757376000000,
                    "issueDate_Display": "‎1404/06/18‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1757408400000,
                    "fromDateTime_Display": "‎1404/06/18‏",
                    "fromTime": "09:00",
                    "toDateTime": 1757444400000,
                    "toDateTime_Display": "‎1404/06/18‏",
                    "toTime": "19:00",
                    "durationMinutes": "10:00",
                    "extensionDateTime": 1757444400000,
                    "extensionDateTime_Display": "‎1404/06/18‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1604313
                },
                {
                    "number": "1489718",
                    "issueDate": 1757376000000,
                    "issueDate_Display": "‎1404/06/18‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1757322000000,
                    "fromDateTime_Display": "‎1404/06/17‏",
                    "fromTime": "09:00",
                    "toDateTime": 1757358000000,
                    "toDateTime_Display": "‎1404/06/17‏",
                    "toTime": "19:00",
                    "durationMinutes": "10:00",
                    "extensionDateTime": 1757358000000,
                    "extensionDateTime_Display": "‎1404/06/17‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1604312
                },
                {
                    "number": "1489717",
                    "issueDate": 1757376000000,
                    "issueDate_Display": "‎1404/06/18‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1757235600000,
                    "fromDateTime_Display": "‎1404/06/16‏",
                    "fromTime": "09:00",
                    "toDateTime": 1757271600000,
                    "toDateTime_Display": "‎1404/06/16‏",
                    "toTime": "19:00",
                    "durationMinutes": "10:00",
                    "extensionDateTime": 1757271600000,
                    "extensionDateTime_Display": "‎1404/06/16‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1604311
                },
                {
                    "number": "1489716",
                    "issueDate": 1757376000000,
                    "issueDate_Display": "‎1404/06/18‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1757149200000,
                    "fromDateTime_Display": "‎1404/06/15‏",
                    "fromTime": "09:00",
                    "toDateTime": 1757185200000,
                    "toDateTime_Display": "‎1404/06/15‏",
                    "toTime": "19:00",
                    "durationMinutes": "10:00",
                    "extensionDateTime": 1757185200000,
                    "extensionDateTime_Display": "‎1404/06/15‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1604310
                },
                {
                    "number": "1489712",
                    "issueDate": 1757376000000,
                    "issueDate_Display": "‎1404/06/18‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1756890000000,
                    "fromDateTime_Display": "‎1404/06/12‏",
                    "fromTime": "09:00",
                    "toDateTime": 1756926000000,
                    "toDateTime_Display": "‎1404/06/12‏",
                    "toTime": "19:00",
                    "durationMinutes": "10:00",
                    "extensionDateTime": 1756926000000,
                    "extensionDateTime_Display": "‎1404/06/12‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1604306
                },
                {
                    "number": "1489711",
                    "issueDate": 1757376000000,
                    "issueDate_Display": "‎1404/06/18‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1756803600000,
                    "fromDateTime_Display": "‎1404/06/11‏",
                    "fromTime": "09:00",
                    "toDateTime": 1756839600000,
                    "toDateTime_Display": "‎1404/06/11‏",
                    "toTime": "19:00",
                    "durationMinutes": "10:00",
                    "extensionDateTime": 1756839600000,
                    "extensionDateTime_Display": "‎1404/06/11‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1604305
                },
                {
                    "number": "1489708",
                    "issueDate": 1757376000000,
                    "issueDate_Display": "‎1404/06/18‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1756630800000,
                    "fromDateTime_Display": "‎1404/06/09‏",
                    "fromTime": "09:00",
                    "toDateTime": 1756666800000,
                    "toDateTime_Display": "‎1404/06/09‏",
                    "toTime": "19:00",
                    "durationMinutes": "10:00",
                    "extensionDateTime": 1756666800000,
                    "extensionDateTime_Display": "‎1404/06/09‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1604302
                },
                {
                    "number": "1489707",
                    "issueDate": 1757376000000,
                    "issueDate_Display": "‎1404/06/18‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1756544400000,
                    "fromDateTime_Display": "‎1404/06/08‏",
                    "fromTime": "09:00",
                    "toDateTime": 1756580400000,
                    "toDateTime_Display": "‎1404/06/08‏",
                    "toTime": "19:00",
                    "durationMinutes": "10:00",
                    "extensionDateTime": 1756580400000,
                    "extensionDateTime_Display": "‎1404/06/08‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1604301
                },
                {
                    "number": "1489702",
                    "issueDate": 1757376000000,
                    "issueDate_Display": "‎1404/06/18‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1756285200000,
                    "fromDateTime_Display": "‎1404/06/05‏",
                    "fromTime": "09:00",
                    "toDateTime": 1756321200000,
                    "toDateTime_Display": "‎1404/06/05‏",
                    "toTime": "19:00",
                    "durationMinutes": "10:00",
                    "extensionDateTime": 1756321200000,
                    "extensionDateTime_Display": "‎1404/06/05‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1604296
                },
                {
                    "number": "1489701",
                    "issueDate": 1757376000000,
                    "issueDate_Display": "‎1404/06/18‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1756198800000,
                    "fromDateTime_Display": "‎1404/06/04‏",
                    "fromTime": "09:00",
                    "toDateTime": 1756234800000,
                    "toDateTime_Display": "‎1404/06/04‏",
                    "toTime": "19:00",
                    "durationMinutes": "10:00",
                    "extensionDateTime": 1756234800000,
                    "extensionDateTime_Display": "‎1404/06/04‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1604295
                },
                {
                    "number": "1489700",
                    "issueDate": 1757376000000,
                    "issueDate_Display": "‎1404/06/18‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1756112400000,
                    "fromDateTime_Display": "‎1404/06/03‏",
                    "fromTime": "09:00",
                    "toDateTime": 1756148400000,
                    "toDateTime_Display": "‎1404/06/03‏",
                    "toTime": "19:00",
                    "durationMinutes": "10:00",
                    "extensionDateTime": 1756148400000,
                    "extensionDateTime_Display": "‎1404/06/03‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1604294
                },
                {
                    "number": "1489697",
                    "issueDate": 1757376000000,
                    "issueDate_Display": "‎1404/06/18‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1755939600000,
                    "fromDateTime_Display": "‎1404/06/01‏",
                    "fromTime": "09:00",
                    "toDateTime": 1755975600000,
                    "toDateTime_Display": "‎1404/06/01‏",
                    "toTime": "19:00",
                    "durationMinutes": "10:00",
                    "extensionDateTime": 1755975600000,
                    "extensionDateTime_Display": "‎1404/06/01‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1604291
                },
                {
                    "number": "1489692",
                    "issueDate": 1757376000000,
                    "issueDate_Display": "‎1404/06/18‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1755680400000,
                    "fromDateTime_Display": "‎1404/05/29‏",
                    "fromTime": "09:00",
                    "toDateTime": 1755716400000,
                    "toDateTime_Display": "‎1404/05/29‏",
                    "toTime": "19:00",
                    "durationMinutes": "10:00",
                    "extensionDateTime": 1755716400000,
                    "extensionDateTime_Display": "‎1404/05/29‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1604286
                },
                {
                    "number": "1489691",
                    "issueDate": 1757376000000,
                    "issueDate_Display": "‎1404/06/18‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1755594000000,
                    "fromDateTime_Display": "‎1404/05/28‏",
                    "fromTime": "09:00",
                    "toDateTime": 1755630000000,
                    "toDateTime_Display": "‎1404/05/28‏",
                    "toTime": "19:00",
                    "durationMinutes": "10:00",
                    "extensionDateTime": 1755630000000,
                    "extensionDateTime_Display": "‎1404/05/28‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1604285
                },
                {
                    "number": "1489690",
                    "issueDate": 1757376000000,
                    "issueDate_Display": "‎1404/06/18‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1755507600000,
                    "fromDateTime_Display": "‎1404/05/27‏",
                    "fromTime": "09:00",
                    "toDateTime": 1755543600000,
                    "toDateTime_Display": "‎1404/05/27‏",
                    "toTime": "19:00",
                    "durationMinutes": "10:00",
                    "extensionDateTime": 1755543600000,
                    "extensionDateTime_Display": "‎1404/05/27‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1604284
                },
                {
                    "number": "1489689",
                    "issueDate": 1757376000000,
                    "issueDate_Display": "‎1404/06/18‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1755421200000,
                    "fromDateTime_Display": "‎1404/05/26‏",
                    "fromTime": "09:00",
                    "toDateTime": 1755457200000,
                    "toDateTime_Display": "‎1404/05/26‏",
                    "toTime": "19:00",
                    "durationMinutes": "10:00",
                    "extensionDateTime": 1755457200000,
                    "extensionDateTime_Display": "‎1404/05/26‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1604283
                },
                {
                    "number": "1489688",
                    "issueDate": 1757376000000,
                    "issueDate_Display": "‎1404/06/18‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1755334800000,
                    "fromDateTime_Display": "‎1404/05/25‏",
                    "fromTime": "09:00",
                    "toDateTime": 1755370800000,
                    "toDateTime_Display": "‎1404/05/25‏",
                    "toTime": "19:00",
                    "durationMinutes": "10:00",
                    "extensionDateTime": 1755370800000,
                    "extensionDateTime_Display": "‎1404/05/25‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1604282
                },
                {
                    "number": "1464592",
                    "issueDate": 1754956800000,
                    "issueDate_Display": "‎1404/05/21‏",
                    "fullName": "بهزاد عابدین زاده",
                    "missionTypeTitle": "دورکاری",
                    "missionTypeCode": 2,
                    "missionTypeCode_Display": "ساعتی",
                    "sourceTitle": "",
                    "destinationTitle": "",
                    "fromDateTime": 1755075600000,
                    "fromDateTime_Display": "‎1404/05/22‏",
                    "fromTime": "09:00",
                    "toDateTime": 1755111600000,
                    "toDateTime_Display": "‎1404/05/22‏",
                    "toTime": "19:00",
                    "durationMinutes": "10:00",
                    "extensionDateTime": 1755111600000,
                    "extensionDateTime_Display": "‎1404/05/22‏",
                    "status": 2,
                    "status_Display": "Official confirmed",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "description": "دورکاری",
                    "id": 1577663
                }
            ];
        }
        const url = 'https://attendance.snappfood.ir/SnappPortal/api/Framework/EntityView/Query';
        //  https://attendance.snappfood.ir/SnappPortal/api/Framework/EntityView/Query
        // const url = 'http://localhost:3000/api/SnappPortal/api/Framework/EntityView/Query';
        const options = {
            method: 'POST',
            headers: {
                accept: '*/*',
                'accept-language': 'en-US,en;q=0.9',
                'content-type': 'application/json',
                cookie: COOKIE,
                origin: 'https://attendance.snappfood.ir',
                priority: 'u=1, i',
                referer: 'https://attendance.snappfood.ir/SnappPortal/apps/hcm-mission-portal/list-mission-documents?componentName=SystemGroup.HCM.Mission&entity=MissionDocument&view=PortalSelfServiceMissionDocuments',
                'sec-ch-ua': '"Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"',
                'sec-ch-ua-mobile': '?0',
                'sec-ch-ua-platform': '"macOS"',
                'sec-fetch-dest': 'empty',
                'sec-fetch-mode': 'cors',
                'sec-fetch-site': 'same-origin',
                'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36',
                'x-requested-with': 'XMLHttpRequest',
                'x-xsrf-token': TOKEN,
            },
            body: '{"entityViewName":"SystemGroup.HCM.Mission/MissionDocument/PortalSelfServiceMissionDocuments","pageSize":50,"pageIndex":0,"searchText":null,"parameters":null,"sorts":null,"filters":null,"source":"list"}'
        };

        try {
            const response = await fetch(url, options);
            const data = await response.json();
            // console.log(data);
            return data;
        } catch (error) {
            console.error(error);
        }
    },
    async createDoorkari({ employeeRef, fromDateTime, toDateTime, durationMinutes }: {
        employeeRef: number,
        fromDateTime: number,
        toDateTime: number,
        durationMinutes: number,
    }): Promise<void> {
        // const fetch = require('node-fetch');
        const url = 'https://attendance.snappfood.ir/SnappPortal/api/HCM/Mission/Portal/MissionDocument/Save';
        const options = {
            method: 'POST',
            headers: {
                accept: 'application/json, text/plain, */*',
                'accept-language': 'en-US,en;q=0.9,fa;q=0.8,de;q=0.7',
                'content-type': 'application/json',
                cookie: COOKIE,
                origin: 'https://attendance.snappfood.ir',
                priority: 'u=1, i',
                referer: 'https://attendance.snappfood.ir/SnappPortal/apps/hcm-mission-portal/mission-document',
                'sec-ch-ua': '"Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"',
                'sec-ch-ua-mobile': '?0',
                'sec-ch-ua-platform': '"macOS"',
                'sec-fetch-dest': 'empty',
                'sec-fetch-mode': 'cors',
                'sec-fetch-site': 'same-origin',
                'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36',
                'x-xsrf-token': TOKEN,
            },
            body: JSON.stringify({
                "entity": {
                    "employeeRef": employeeRef,
                    "fromDateTime": fromDateTime,
                    "durationDays": 0,
                    "durationMinutes": durationMinutes,
                    "toDateTime": toDateTime,
                    "extensionDateTime": toDateTime,
                    "missionTypeRef": 5,
                    "issueDate": 1763424000000,
                    "dispatchingDepartmentRef": null,
                    "sourceRef": null,
                    "destinationRef": null,
                    "batchMissionDocumentRef": null,
                    "officialConfirmerEmployeeRef": null,
                    "financialConfirmerEmployeeRef": null, "number": null,
                    "missionDocumentReports": [],
                    "description": "دورکاری",
                    "financialConfirmationNumber": null,
                    "officialConfirmationNumber": null,
                    "toDateTimeTitle": toDateTime.toString(),
                    "extensionDateTimeTitle": toDateTime.toString(),
                    "officialConfirmationDateTime": null,
                    "financialConfirmationDateTime": null,
                    "distance": null,
                    "travelTypeCode": null,
                    "accommodationTypeCode": null,
                    "__state": 2
                }, "extensions": []
            })
        };

        try {
            const response = await fetch(url, options);
            const data = await response.json();
            console.log(data);
        } catch (error) {
            console.error(error);
            throw 'failed to submit';
        }
    },
    async getEmployeeName(): Promise<string> {
        if (IS_DEV)
            return 'بهزاد تست';
        const url = 'https://attendance.snappfood.ir/SnappPortal/api/FrontEnd/Shell/StaticData';
        const options = {
            method: 'GET',
            headers: {
                accept: '*/*',
                'accept-language': 'en-US,en;q=0.9,fa;q=0.8,de;q=0.7',
                cookie: '_gcl_au=1.1.1169149196.1761657323; _ym_uid=1761657324499702902; _ym_d=1761657324; analytics_campaign={%22source%22:%22google%22%2C%22medium%22:%22organic%22}; _hjSessionUser_3300609=eyJpZCI6Ijk1NzIyODNiLTRmZTEtNTQzOC1hNDVlLTBkMzlmNDgxNTM2OSIsImNyZWF0ZWQiOjE3NjI4NjE3NDE4MDEsImV4aXN0aW5nIjp0cnVlfQ==; _clck=1loqhaz%5E2%5Eg11%5E0%5E2127; _ga_W2FYNR9BLD=GS2.1.s1763301411$o12$g0$t1763302700$j60$l0$h0; rl_page_init_referrer=RudderEncrypt%3AU2FsdGVkX1%2F58r4TtoD5ySeXlyF3g1JKjZGr%2F2xV0c8%3D; _ga=GA1.2.470503137.1761640339; rl_session=RudderEncrypt%3AU2FsdGVkX1%2FANifacMsHVehkyq8w%2FRFjWELNrZOz0q4vNvq0HU7aLgm6bKDW5iXVQW1cJ5E51g7e5KvvTC56VUit9xJCbgmmSpTNvumT4EXrDWT7HCv1ygMrSGxfNhLvTyEfIlrub8lCioatfPfhsg%3D%3D; rl_user_id=RudderEncrypt%3AU2FsdGVkX1%2Behg2JiAbifjnfDj5q1p45r11VNMLO9grUpI0VPnBcFSyay22rQ3xr; rl_trait=RudderEncrypt%3AU2FsdGVkX1%2BB62yNIbsQHsbXv3UlBF%2FM2Kr%2BmlckdElyEIRohdwRW358ryI1c42fsx0NENF9JGBsjLdSHOOlDySBdjw59XBe2idxkl6OCucAXh0W9EOnc7pFeAK%2BhO1m; rl_group_id=RudderEncrypt%3AU2FsdGVkX1%2BI26xV4zCcEx9TA%2FY9y9eh1u6uo4JmGIQ%3D; rl_group_trait=RudderEncrypt%3AU2FsdGVkX19Dm0sv9ptM55Fy0rdU1V6nZva6BMC7JZs%3D; rl_anonymous_id=RudderEncrypt%3AU2FsdGVkX1%2F1DK01RTthcJCMPA924a0w1pmFLWO8a48qDTu1CZkev5Mdfj9MpP8oe0ArQpj91v07grNmpc8MOQ%3D%3D; amplitude_id_cf620211dc906be4ab7c92f52766759dsnappfood.ir=eyJkZXZpY2VJZCI6IjQ3YjVlOGQ2LTNjMTgtNGYxOS1hOTRmLTJlMjk3YjJhOTZhZVIiLCJ1c2VySWQiOm51bGwsIm9wdE91dCI6ZmFsc2UsInNlc3Npb25JZCI6MTc2MzQ1MDU0MzE2OCwibGFzdEV2ZW50VGltZSI6MTc2MzQ1MTA1Mzk2MCwiZXZlbnRJZCI6MCwiaWRlbnRpZnlJZCI6MCwic2VxdWVuY2VOdW1iZXIiOjB9; rahkaran-culture=c=fa-IR|uic=fa-IR; rahkaran-xsrf=CfDJ8OXOtpZ5WotGuQAshYdU0XvtD8GGr6St-7vU1WtXYdhx7mTx3MoMki0f2DoDE72KE1_CeAU3ovKdywuem8UzA9ED_3LS5ri_XctKOfgSgc7Rs8gRM-pqkBbtW0UYvUl_8KriPu6AFDQZHAZShr0lnqo; XSRF-TOKEN=CfDJ8OXOtpZ5WotGuQAshYdU0Xuf0-BbwufpF7o1suMLyJN_mjiynsBduV0jJJaDCkUlPgcYRoumQYFIRJEIxz_5Xsy3bTNtV8IkJjmsZKV-9CIqqt9qMqnfFBN_eNwWNgm-AMcm0y5zF965PkhEXVP-kwsYv_jz-iEM-S1mkKQAJrP1ovZUL_X1OMAZhX1iUz0Log; rahkaran-auth=CfDJ8OXOtpZ5WotGuQAshYdU0XucpqR-TuVYLme6oIS5Hp-ds16YAEXH2bsdoB4f9PXgolMYiJXPFej8gocIeD8wTHHQaf6agSxw6eOwLAmPOXtRIXsU3CxTuwnbf3N299v8KG4X1_AqVuKLAuC2KzDnU1tR7P1hKNJL6I6aGD1aIqKtNNq9MvsLgmucyGlOw1XFKBvOi5JD3VtRjKJfzPh_hk18lBO19VSq92a4fvTOW-SkaoxwBFFnk9z_pLm3zWt0Zc_1uqaCG9voOH4GLqkXbUBWfOp0KYT_3GXp8RniVjb9Wq-pLNVzewdpqjcra3EikcM97I8lKzTQIdosSV90ppHd8v21dxDYLy70x26-EbLhyf_R5xiai5BL0rIrCKde2iVXXqeQSG_09MdYt0TZdWj_FmRMCwtdoM3akaVqNAZFqGhhWC_Q_GvqEpvyzXxkNXIhMe9pFP5ofCIUubVycT5PSWTlRj6jP-AEsR0aVPBtj2c8SsEttwKcpyvcW5EN4QblxL-82-bVPlOmCau8TK6YD-UhOQKUY7UVOSCvMUaGTYT9bL08RQ94FBEtnmd4Fso-FS_INjMbcJQTAGs12jAsJtd-1rmcjTI8uSg5qBY-2BVg19DVIrgveiU1JxhhYyxuJ2DcJSqmHrWFrN2TWaM',
                priority: 'u=1, i',
                referer: 'https://attendance.snappfood.ir/SnappPortal/',
                'sec-ch-ua': '"Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"',
                'sec-ch-ua-mobile': '?0',
                'sec-ch-ua-platform': '"macOS"',
                'sec-fetch-dest': 'empty',
                'sec-fetch-mode': 'cors',
                'sec-fetch-site': 'same-origin',
                'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36',
                'x-xsrf-token': 'CfDJ8OXOtpZ5WotGuQAshYdU0Xuf0-BbwufpF7o1suMLyJN_mjiynsBduV0jJJaDCkUlPgcYRoumQYFIRJEIxz_5Xsy3bTNtV8IkJjmsZKV-9CIqqt9qMqnfFBN_eNwWNgm-AMcm0y5zF965PkhEXVP-kwsYv_jz-iEM-S1mkKQAJrP1ovZUL_X1OMAZhX1iUz0Log'
            }
        };

        try {
            const response = await fetch(url, options);
            const data = await response.json();
            return data.user.displayName;
            // console.log(data);
        } catch (error) {
            console.error(error);
        }
    },
    async getCurrentEmployeeId(): Promise<number> {
        if (IS_DEV)
            return 6305;
        const url = 'https://attendance.snappfood.ir/SnappPortal/api/HCM/Mission/Portal/MissionDocument/getCurrentEmployeeId';
        const options = {
            method: 'GET',
            headers: {
                accept: 'application/json, text/plain, */*',
                'accept-language': 'en-US,en;q=0.9,fa;q=0.8,de;q=0.7',
                cookie: COOKIE,
                priority: 'u=1, i',
                referer: 'https://attendance.snappfood.ir/SnappPortal/apps/hcm-mission-portal/mission-document',
                'sec-ch-ua': '"Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"',
                'sec-ch-ua-mobile': '?0',
                'sec-ch-ua-platform': '"macOS"',
                'sec-fetch-dest': 'empty',
                'sec-fetch-mode': 'cors',
                'sec-fetch-site': 'same-origin',
                'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36',
                'x-xsrf-token': TOKEN,
            }
        };
        try {
            const response = await fetch(url, options);
            const data = await response.text();
            return parseInt(data);
        } catch (error) {
            console.error(error);
        }
    },
    async getMorakhasiList(): Promise<LeaveRequest[]> {
        if (IS_DEV) {
            return [
                {
                    "requestNumber": "520576",
                    "requestDate": 1763769600000,
                    "requestDate_Display": "‎1404/09/01‏",
                    "fullName": "بهزاد عابدین زاده",
                    "leaveTypeTitle": "مرخصی استحقاقی",
                    "isDailyTitle": "روزانه",
                    "fromDateTime": 1763510400000,
                    "fromDateTime_Display": "‎00:00 1404/08/28‏",
                    "toDateTime": 1763510400000,
                    "toDateTime_Display": "‎00:00 1404/08/28‏",
                    "substituteCode": "",
                    "substituteName": "",
                    "status": 1,
                    "status_Display": "ذخیره شده",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "durationTitle": "07:00",
                    "id": 558868
                },
                {
                    "requestNumber": "505238",
                    "requestDate": 1760227200000,
                    "requestDate_Display": "‎1404/07/20‏",
                    "fullName": "بهزاد عابدین زاده",
                    "leaveTypeTitle": "مرخصی استحقاقی",
                    "isDailyTitle": "روزانه",
                    "fromDateTime": 1757808000000,
                    "fromDateTime_Display": "‎00:00 1404/06/23‏",
                    "toDateTime": 1757980800000,
                    "toDateTime_Display": "‎00:00 1404/06/25‏",
                    "substituteCode": "",
                    "substituteName": "",
                    "status": 10,
                    "status_Display": "تایید نهایی",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "durationTitle": "27:00",
                    "id": 541401
                },
                {
                    "requestNumber": "486247",
                    "requestDate": 1754956800000,
                    "requestDate_Display": "‎1404/05/21‏",
                    "fullName": "بهزاد عابدین زاده",
                    "leaveTypeTitle": "مرخصی استحقاقی",
                    "isDailyTitle": "روزانه",
                    "fromDateTime": 1752364800000,
                    "fromDateTime_Display": "‎00:00 1404/04/22‏",
                    "toDateTime": 1752537600000,
                    "toDateTime_Display": "‎00:00 1404/04/24‏",
                    "substituteCode": "",
                    "substituteName": "",
                    "status": 10,
                    "status_Display": "تایید نهایی",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "durationTitle": "27:00",
                    "id": 521241
                },
                {
                    "requestNumber": "428159",
                    "requestDate": 1738972800000,
                    "requestDate_Display": "‎1403/11/20‏",
                    "fullName": "بهزاد عابدین زاده",
                    "leaveTypeTitle": "مرخصی استحقاقی",
                    "isDailyTitle": "روزانه",
                    "fromDateTime": 1737504000000,
                    "fromDateTime_Display": "‎00:00 1403/11/03‏",
                    "toDateTime": 1737504000000,
                    "toDateTime_Display": "‎00:00 1403/11/03‏",
                    "substituteCode": "",
                    "substituteName": "",
                    "status": 10,
                    "status_Display": "تایید نهایی",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "durationTitle": "08:00",
                    "id": 459098
                },
                {
                    "requestNumber": "389129",
                    "requestDate": 1725840000000,
                    "requestDate_Display": "‎1403/06/19‏",
                    "fullName": "بهزاد عابدین زاده",
                    "leaveTypeTitle": "مرخصی استحقاقی",
                    "isDailyTitle": "روزانه",
                    "fromDateTime": 1725321600000,
                    "fromDateTime_Display": "‎00:00 1403/06/13‏",
                    "toDateTime": 1725321600000,
                    "toDateTime_Display": "‎00:00 1403/06/13‏",
                    "substituteCode": "",
                    "substituteName": "",
                    "status": 10,
                    "status_Display": "تایید نهایی",
                    "creator": "بهزاد عابدین زاده",
                    "branchTitle": "",
                    "durationTitle": "09:00",
                    "id": 417373
                }
            ];
        }
        const url = 'https://attendance.snappfood.ir/SnappPortal/api/Framework/EntityView/Query';
        const options = {
            method: 'POST',
            headers: {
                accept: '*/*',
                'accept-language': 'en-US,en;q=0.9,fa;q=0.8,de;q=0.7',
                'content-type': 'application/json',
                cookie: COOKIE,
                origin: 'https://attendance.snappfood.ir',
                priority: 'u=1, i',
                referer: 'https://attendance.snappfood.ir/SnappPortal/apps/hcm-leave-portal/list-leave-requests?componentName=SystemGroup.HCM.Leave&entity=LeaveRequest&view=PortalAllSelfServiceEmployeeLeaveRequests',
                'sec-ch-ua': '"Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"',
                'sec-ch-ua-mobile': '?0',
                'sec-ch-ua-platform': '"macOS"',
                'sec-fetch-dest': 'empty',
                'sec-fetch-mode': 'cors',
                'sec-fetch-site': 'same-origin',
                'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36',
                'x-requested-with': 'XMLHttpRequest',
                'x-xsrf-token': TOKEN
            },
            body: '{"entityViewName":"SystemGroup.HCM.Leave/LeaveRequest/PortalAllSelfServiceEmployeeLeaveRequests","pageSize":50,"pageIndex":0,"searchText":null,"parameters":null,"sorts":null,"filters":null,"source":"list"}'
        };

        try {
            const response = await fetch(url, options);
            const data = await response.json();
            return data;
        } catch (error) {
            console.error(error);
        }
    },
    async getAllStatusList({
        employeeId, fromDate, toDate
    }: {
        employeeId: number,
        fromDate: string,
        toDate: string,
    }): Promise<AttendenceStatusDto[]> {
        if (IS_DEV)
            return MOCK_HOZURI_DATA;
        const url = `https://attendance.snappfood.ir/SnappPortal/api/HCM/AttendanceCalculation/Portal/AttendanceCalculation/GetAllPairAttendanceDataInfo?EmployeeId=${employeeId}&FromDate=${fromDate}&ToDate=${toDate}`;
        const options = {
            method: 'GET',
            headers: {
                accept: 'application/json, text/plain, */*',
                'accept-language': 'en-US,en;q=0.9,fa;q=0.8,de;q=0.7',
                cookie: COOKIE,
                priority: 'u=1, i',
                referer: 'https://attendance.snappfood.ir/SnappPortal/apps/hcm-leave-portal/m/leave-request',
                'sec-ch-ua': '"Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"',
                'sec-ch-ua-mobile': '?1',
                'sec-ch-ua-platform': '"Android"',
                'sec-fetch-dest': 'empty',
                'sec-fetch-mode': 'cors',
                'sec-fetch-site': 'same-origin',
                'user-agent': 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Mobile Safari/537.36',
                'x-xsrf-token': TOKEN,
            }
        };

        try {
            const response = await fetch(url, options);
            const data = await response.json();
            // console.log(data);
            return data;
        } catch (error) {
            console.error(error);
        }
    }
}